pipeline {
    agent any

    environment {
        REGISTRY    = 'localhost:9080'          // registry visto por el Docker del host
        NEXUS_URL   = 'http://nexus:8081'       // Nexus visto desde cicd_network
        NEXUS_CREDS = credentials('nexus-credentials')
    }

    triggers {
        githubPush()
    }

    stages {
        stage('Checkout & Test') {
            steps {
                checkout scm
                script {
                    def sha = sh(script: 'git rev-parse --short=7 HEAD', returnStdout: true).trim()
                    env.VERSION = "1.0.${env.BUILD_NUMBER}-${sha}"
                    echo "Versión inmutable: ${env.VERSION}"
                }
                dir('backend') {
                    sh 'mvn -B test'
                }
            }
            post {
                always {
                    junit 'backend/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Package & Tag Inmutable') {
            steps {
                dir('backend') {
                    sh 'mvn -B package -DskipTests -Drevision=$VERSION'
                    sh 'docker build -t $REGISTRY/studytrack-api:$VERSION .'
                }
                dir('frontend') {
                    sh 'docker build --build-arg VITE_API_URL=http://localhost:8080 -t $REGISTRY/studytrack-frontend:$VERSION .'
                }
            }
        }

        stage('Publish to Nexus') {
            steps {
                writeFile file: 'ci-settings.xml', text: '''<settings>
  <servers>
    <server>
      <id>nexus-releases</id>
      <username>${env.NEXUS_CREDS_USR}</username>
      <password>${env.NEXUS_CREDS_PSW}</password>
    </server>
  </servers>
</settings>'''
                dir('backend') {
                    sh 'mvn -B deploy -DskipTests -Drevision=$VERSION -Dnexus.url=$NEXUS_URL -s ../ci-settings.xml'
                }
                sh '''
                    echo "$NEXUS_CREDS_PSW" | docker login $REGISTRY -u "$NEXUS_CREDS_USR" --password-stdin
                    docker push $REGISTRY/studytrack-api:$VERSION
                    docker push $REGISTRY/studytrack-frontend:$VERSION
                '''
            }
        }

        stage('Deploy & Smoke Test') {
            steps {
                sh 'IMAGE_TAG=$VERSION docker compose -f deploy/docker-compose.yml up -d'
                sh '''
                    for i in $(seq 1 20); do
                        if curl -fs http://studytrack-api:8080/api/tasks; then
                            echo "Smoke test OK"; exit 0
                        fi
                        echo "Intento $i fallido, reintentando en 5s..."; sleep 5
                    done
                    echo "Smoke test FALLÓ"; exit 1
                '''
            }
        }
    }
}