services:
  nexus:
    image: sonatype/nexus3:3.68.1
    container_name: nexus
    networks:
      - cicd_network
    ports:
      - "${NEXUS_UI_PORT}:8081"                # UI web
      - "${NEXUS_DOCKER_REGISTRY_PORT}:8082"   # registry Docker (docker-hosted)
    volumes:
      - ./nexus_data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms1g -Xmx1g -XX:MaxDirectMemorySize=1g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/service/rest/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

networks:
  cicd_network:
    external: true